### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-arlo

### ISSUE THREAD

**Issue by 0minousC0d3** [homebridge-plugins/homebridge-arlo#1]
When I startup homebridge on my server, it throws an error that looks like this:
```
ERROR LOADING PLUGIN homebridge-arlo
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/index.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
Everything else in homebridge works except for this. Thank you!

**Comment by devbobo** [comment]
@R3C0Nx00 weird, I've been running this for months with no issues. What version of `NodeJS` are you running ?

**Comment by MrBeaker** [comment]
I had the same issue. You need to update your version of NodeJS for it to load.

**Comment by moxify** [comment]
Which Version of NodeJS is required?

**Comment by devbobo** [comment]
At least Node version 6.0

**Comment by 0minousC0d3** [comment]
I apologize. I checked and I was running an older version of Node.js. I apologize! Thanks!
