### ISSUE TITLE
plugin crashing upon install

### ISSUE THREAD

**Issue by justinsail** [homebridge-plugins/homebridge-arlo#122]
**Describe The Bug:**
Just installed the plugin as a child bridge and also created a guest account with the Arlo app but the plugin crashes at startup.

**To Reproduce:**
Happens at boot of Homebridge (raspberry Pi 4 version) and crashes, then starts all over and crashes again. I created it as a child bridge so it doesn't take down the rest of my system but I had to disable it for now.

**Logs:**
[29/04/2021, 13:18:15] Homebridge v1.3.4 (Arlo) is running on port 30092.
[29/04/2021, 13:18:18] [Arlo] Found: Camera - garage [52M1837BBB375]

/usr/local/lib/node_modules/homebridge-arlo/ArloCameraSource.js:26
        this.videoProcessor = config.videoProcessor || 'ffmpeg';
                                     ^
TypeError: Cannot read property 'videoProcessor' of undefined
    at new ArloCameraSource (/usr/local/lib/node_modules/homebridge-arlo/ArloCameraSource.js:26:38)
    at ArloPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-arlo/index.js:94:45)
    at ArloPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:147:26)
    at Arlo.emit (events.js:315:20)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:53:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:387:11)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
[29/04/2021, 13:18:19] [Arlo] Child bridge process ended
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
            "name": "Arlo",
            "email": "me@justinbradshaw.com",
            "password": "xxxx",
            "include_cameras": true,
            "_bridge": {
                "username": "0E:17:2B:16:25:19",
                "port": 30092
            },
            "platform": "Arlo"
```

**Screenshots:**

**Environment:**

* **Node.js Version**:v14.16.1
* **NPM Version**: v7.11.1
* **Homebridge Version**: 1.3.4
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.41.1 - © 2021 oznu

* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by dotfortun3-code** [comment]
Looks like the config isn't generating properly if none of the default fields are set under streaming. Just go under Streaming > Video Processor and set that to ffmpeg and it will work. The placeholder text is there, but the field is technically blank. Once you save it, it should start properly.

**Comment by dotfortun3-code** [comment]
#123 

This fixes this issue.

**Comment by justinsail** [comment]
Thank you! Yes, it does fix the initial load and crash problem. Now I'm having another one you may be able to help with. Seems that it's finding my cameras, but not able to "read property 'id' of undefined"
It's also causing a reload of the home bridge web UI every several seconds

down below in the logs, it suggests adding each camera as a separate bridge. Is this something that's normal and will it fix the errors in my log?

[03/05/2021, 15:53:36] [Arlo] Found: Camera - garage [52M1837BBB375]
TypeError: Cannot read property 'id' of undefined
    at Arlo.notify (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:360:35)
    at ArloCamera.get (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:17)
    at new ArloCameraAccessory (/usr/local/lib/node_modules/homebridge-arlo/index.js:297:21)
    at ArloPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-arlo/index.js:96:48)
    at ArloPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:147:26)
    at Arlo.emit (events.js:315:20)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:53:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:387:11)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
undefined
....
Preparing Advertiser for 'garage 4ECD' using bonjour-hap backend!
....
[03/05/2021, 15:53:36] garage 4ECD is running on port 33559.
[03/05/2021, 15:53:36] Please add [garage 4ECD] manually in Home app. Setup Code: xxx-xx-xxx

**Comment by justinsail** [comment]
UPDATE: I went ahead and added my 3 cameras individually with the setup code (all 3 had the same one, which is interesting, and they were discovered by HomeKit, also interesting... that must be the "using bonjour-hap backend!" stuff) 

and THEY WORK! 

So that's very cool. Thanks for writing and supporting this plugin! 

but, I'm still getting the property 'id' error listed above for all three cameras and I feel like it's making the system a little unstable, especially the homebridge UI. Any possible way to have the plugin stop looking for the camera ID now that they've been added separately? 

THANK YOU. I'm one step closer to unifying my smarthome. Just have Wink, Tuya, and Flume to go!

**Comment by justinsail** [comment]
Still getting this error in my logs. Anyone have an idea how to fix?

[19/05/2021, 14:56:40] [Arlo] Found: Camera - Kitchen porch 
TypeError: Cannot read property 'id' of undefined
    at Arlo.notify (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:360:35)
    at ArloCamera.get (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:17)
    at new ArloCameraAccessory (/usr/local/lib/node_modules/homebridge-arlo/index.js:297:21)
    at ArloPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-arlo/index.js:96:48)
    at ArloPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:147:26)
    at Arlo.emit (events.js:315:20)
    at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:53:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:387:11)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
undefined
TypeError: Cannot read property 'id' of undefined
    at Arlo.notify (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:360:35)
    at ArloCamera.get (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:17)
    at ArloCameraAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:317:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
undefined
TypeError: Cannot read property 'id' of undefined
    at Arlo.notify (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:360:35)
    at ArloCamera.get (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:17)
    at ArloCameraAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:317:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
undefined
TypeError: Cannot read property 'id' of undefined
    at Arlo.notify (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:360:35)
    at ArloCamera.get (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:17)
    at ArloCameraAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:317:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
undefined
