### ISSUE TITLE
Camera streaming broke suddenly

### ISSUE THREAD

**Issue by ultrathew** [homebridge-plugins/homebridge-arlo#129]
**Describe The Bug:**
Cameras will no longer stream in Home app. This had been working fine for nearly a year with no change to the config.

**To Reproduce:**
Cameras throw errors as soon as HB launches. Will not stream when connected to directly in Home app.

**Expected behavior:**
Cameras provide snapshot and stream video. Instead getting "No response" in Home app.

**Logs:**

```
Getting the following on HB launch:

[23/05/2021, 10:54:44] [homebridge-arlo] This plugin slows down Homebridge. The write handler for the characteristic 'Setup Endpoints' on the accessory 'Back Roof 4281' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[23/05/2021, 10:54:52] [Arlo] Snapshot request: Camera Back Roof [48B4597PE01AF]
[Back Roof 4281] Unhandled error thrown inside snapshot request handler: Error: options.uri is a required argument
    at Request.init (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:231:31)
    at new Request (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/index.js:53:10)
    at Function.get (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/index.js:61:12)
    at Arlo.downloadSnapshot (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:262:13)
    at ArloCamera.downloadSnapshot (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:20:17)
    at ArloCameraSource.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge-arlo/ArloCameraSource.js:81:21)
    at LegacyCameraSourceAdapter.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/Camera.ts:59:23)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
```

**Homebridge Config:**

        {
            "name": "Arlo",
            "email": "**EMAIL**",
            "password": "**PASSWORD**",
            "include_cameras": true,
            "streaming": {
                "videoDecoder": "h264_mmal",
                "videoEncoder": "h264_omx",
                "packetSize": "500",
                "maxBitrate": "300"
            },
            "platform": "Arlo"
        }

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.16.1
* **NPM Version**: v7.11.1
* **Homebridge Version**:  v1.3.4
* **Homebridge Config UI X Plugin Version**: v4.41.1
* **Operating System**: Raspian / Homebridge Image

**Comment by ultrathew** [comment]
I just managed to solve this on my own. I'm using a dedicated Arlo account for Homebridge, and I realized that when I tried to confirm that account was working fine by logging in on the Arlo site that none of my four cameras were appearing in that account. I fixed this by manually removing and then re-adding all cameras from the Homebridge-dedicated Arlo account. I restarted Homebridge and all is working normally again.
