### ISSUE TITLE
Cannot run homebridge

### ISSUE THREAD

**Issue by sdorilas** [homebridge-plugins/homebridge-arlo#5]
====================
[8/12/2017, 3:51:44 PM] ERROR LOADING PLUGIN homebridge-arlo:
[8/12/2017, 3:51:44 PM] Error: Plugin /usr/local/lib/node_modules/homebridge-arlo requires a HomeBridge version of >=0.4.1 which does not satisfy the current HomeBridge version of 0.3.4. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:112:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:108:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:43:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[8/12/2017, 3:51:44 PM] ====================
[8/12/2017, 3:51:47 PM] Loaded plugin: homebridge-nest
[8/12/2017, 3:51:47 PM] Registering platform 'homebridge-nest.Nest'
[8/12/2017, 3:51:47 PM] ---
[8/12/2017, 3:51:48 PM] Loaded plugin: homebridge-philipshue
[8/12/2017, 3:51:48 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[8/12/2017, 3:51:48 PM] ---
[8/12/2017, 3:51:48 PM] Loaded plugin: homebridge-platform-myq
[8/12/2017, 3:51:48 PM] Registering platform 'homebridge-platform-myq.MyQ'
[8/12/2017, 3:51:48 PM] ---
[8/12/2017, 3:51:48 PM] Loaded plugin: homebridge-xbox-one
[8/12/2017, 3:51:48 PM] Registering accessory 'homebridge-xbox-one.Xbox'
[8/12/2017, 3:51:48 PM] ---
[8/12/2017, 3:51:48 PM] Loaded config.json with 0 accessories and 3 platforms.
[8/12/2017, 3:51:48 PM] ---
[8/12/2017, 3:51:48 PM] Loading 3 platforms...
[8/12/2017, 3:51:48 PM] Initializing Nest platform...
[8/12/2017, 3:51:48 PM] Fetching Nest devices.
[8/12/2017, 3:51:48 PM] [MyQ Platform] Initializing MyQ platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Arlo' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by devbobo** [comment]
Did you read the error message ?

**Error: Plugin /usr/local/lib/node_modules/homebridge-arlo requires a HomeBridge version of >=0.4.1 which does not satisfy the current HomeBridge version of 0.3.4. You may need to upgrade your installation of HomeBridge.**

**Comment by sdorilas** [comment]
lol yes David, I read the message. But when I check the version of homebridge I get the 5.3.0 -- that's what I'm not understanding.

**Comment by devbobo** [comment]
Are you sure you aren't referring to the version of NodeJS that you are using ? The current version of Homebridge is only up to 0.4.22.

**Comment by devbobo** [comment]
either way, running `sudo npm install -g --unsafe-perm homebridge` will upgrade you to the most recent version

**Comment by sdorilas** [comment]
Thank you so much! That updated it. Now I receive the following:

====================
[8/13/2017, 7:46:35 PM] ERROR LOADING PLUGIN homebridge-arlo:
[8/13/2017, 7:46:35 PM] ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
